version: '3'

services:
  llm-quest:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./results:/app/results
      - ./metrics:/app/metrics
    env_file:
      - .env
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
