[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "llm_quest_benchmark"
version = "0.1.0"
description = "LLM Quest Benchmark using Space Rangers quests"
authors = [
    {name = "Kirill Korikov", email = "kirill.korikov@gmail.com"},
]
dependencies = [
    "rich>=10.0.0",
    "typer>=0.9.0",
    "jinja2>=3.0.0",
    "openai>=1.0.0",
    "litellm>=1.0.0",
    "anthropic>=0.7.0",
    "pytest>=7.0.0",
    "pytest-timeout>=2.0.0",
    "pytest-cov>=4.0.0",
    "pytest-xdist>=3.0.0",
    "pytest-sugar>=0.9.0",
    "pytest-clarity>=1.0.0",
    "json-repair>=0.39.0",
]

[project.optional-dependencies]
dev = [
    "pre-commit",
    "yapf>=0.34.0",
    "isort>=5.13.0",
    "pytest>=8.0.0",
    "pytest-cov>=4.1.0",
    "pytest-timeout>=2.0.0",
    "pytest-xdist>=3.0.0",
    "pytest-sugar>=0.9.0",
    "pytest-clarity>=1.0.0",
]

[project.scripts]
llm-quest = "llm_quest_benchmark.executors.cli.commands:app"


[tool.setuptools]
packages = ["llm_quest_benchmark"]

[tool.setuptools.package-data]
"llm_quest_benchmark" = [
    "prompt_templates/*.jinja",
    "scripts/*.ts"
]
