[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["llm_quest_benchmark/tests"]
python_files = ["test_*.py"]
addopts = "-v --tb=short"
markers = [
    "integration: marks tests as integration tests",
    "unit: marks tests as unit tests",
]

[tool.ruff]
line-length = 100
target-version = "py39"
select = ["E", "F", "B", "I"]
ignore = ["E501"]  # Line too long

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]  # Unused imports

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true

[project]
name = "llm_quest_benchmark"
version = "0.1.0"
description = "LLM Quest Benchmark using Space Rangers quests"
authors = [
    {name = "Your Conscience", email = "conscience@example.com"},
]
dependencies = [
    # Core dependencies
    "rich>=10.0.0",
    "typer>=0.9.0",
    "jinja2>=3.0.0",
    "openai>=1.0.0",
    "litellm>=1.0.0",
    "pytest>=7.0.0",
    "pytest-timeout>=2.0.0",
    "pytest-cov>=4.0.0",
    "pytest-xdist>=3.0.0",
    "pytest-sugar>=0.9.0",
    "pytest-clarity>=1.0.0",
]

[project.optional-dependencies]
dev = [
    "pre-commit",
    "yapf>=0.34.0",
    "isort>=5.13.0",
    "pytest>=8.0.0",
    "pytest-cov>=4.1.0"
]

[project.scripts]
llm-quest = "llm_quest_benchmark.executors.cli.commands:app"

[tool.setuptools]
packages = ["llm_quest_benchmark"]

[tool.setuptools.package-data]
"llm_quest_benchmark" = [
    "prompt_templates/*.jinja",
    "scripts/*.ts"
]