[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.uv]
resolution = "highest"

[project]
name = "llm_quest_benchmark"
version = "0.2.0"
description = "Benchmark LLM performance on Space Rangers text quests"
requires-python = ">=3.8"
dependencies = [
    # Core dependencies
    "pydantic>=2.0.0",
    "jinja2>=3.1.0",
    "python-dotenv>=1.0.0",

    # LLM and API
    "litellm>=1.0.0",

    # TextArena integration
    "textarena>=0.3.2",
    "uvicorn>=0.29.0",
    "fastapi>=0.114.0",
    "websockets>=12.0",

    # CLI and rendering
    "rich>=13.0.0",
    "typer>=0.11.0",
    "typing-extensions>=4.0.0"
]

[project.optional-dependencies]
dev = [
    "pre-commit",
    "yapf>=0.34.0",
    "isort>=5.13.0",
    "pytest>=8.0.0",
    "pytest-cov>=4.1.0"
]

[project.scripts]
llm-quest = "llm_quest_benchmark.executors.cli.commands:app"

[tool.setuptools]
packages = ["llm_quest_benchmark"]

[tool.setuptools.package-data]
"llm_quest_benchmark" = [
    "prompt_templates/*.jinja",
    "scripts/*.ts"
]