# Main LLM benchmark configuration
quests:
  - quests/test  # Example quests dir, will be replaced with actual quest paths
agents:
  - model: claude-3-5-sonnet-latest
    skip_single: true
    temperature: 0.5
    system_template: system_role.jinja
    action_template: reasoning.jinja
  - model: gpt-4o
    skip_single: true
    temperature: 0.5
    system_template: system_role.jinja
    action_template: reasoning.jinja
debug: false
quest_timeout: 90
max_workers: 2