# Main LLM benchmark configuration
quests:
  - quests/test  # Example quests dir, will be replaced with actual quest paths
agents:
  # - model: random_choice
  - model: gpt-4o
    template: reasoning.jinja
    temperature: 0.3
    skip_single: true
  - model: gpt-4o
    template: reasoning.jinja
    temperature: 0.7
    skip_single: true
debug: false
quest_timeout: 60
max_workers: 2
output_dir: metrics/benchmarks