# Main LLM benchmark configuration
quests:
  - quests/kr1
agents:
  - model: claude-3-5-sonnet-20241022
    template: reasoning.jinja
    temperature: 0.4
    skip_single: true
  - model: gpt-4o
    template: reasoning.jinja
    temperature: 0.4
    skip_single: true
debug: false
quest_timeout: 120
max_workers: 3
output_dir: metrics/first