# Main LLM benchmark configuration
quests:
  - quests/kr1
agents:
  - model: random_choice
  - model: gpt-4o-mini
    template: default.jinja
    temperature: 0.3
  - model: gpt-4o
    template: reasoning.jinja
    temperature: 0.3
  - model: sonnet
    template: reasoning.jinja
    temperature: 0.3
debug: false
quest_timeout: 120
max_workers: 2
output_dir: metrics/benchmarks